### ISSUE TITLE
"Apply some workload"

### ISSUE THREAD

**Issue by SteinRobert** [gefyrahq/gefyrahq.github.io#10]
The part in the getting started section which says "apply some workload"...

Probably it would make some sense to provide the users with an url - otherwise they are basically forced to clone the repo or make up their own workload, which then makes it probably harder to follow the guide.

**Comment by tschale** [comment]
Sounds good. We might just link to the url of `testing/workloads/hello.yaml`, or do you have something else in mind?

**Comment by SteinRobert** [comment]
Exactly. I currently reworking the getting started sections anyways. I'll tackle that.

**Comment by SteinRobert** [comment]
This is done :)
