### ISSUE TITLE
Add link to feedback form to Website

### ISSUE THREAD

**Issue by Truthans** [gefyrahq/gefyrahq.github.io#63]
To collect more user feedback about gefyra I'd like to add the link to the following feedback form on the website on the following pages:
https://gefyra.dev/
https://gefyra.dev/getting-started/
https://gefyra.dev/docker-desktop-extension/

Best case we could add it in the header next to [CLI reference] too. Here is the link to the feedback form:
https://forms.gle/AWT9NparpTVk8E978

**Comment by SteinRobert** [comment]
Done!
