### ISSUE TITLE
Docs: missing steps in some "Getting Started"s

### ISSUE THREAD

**Issue by chrisegner** [gefyrahq/gefyrahq.github.io#95]
### What happened?

There are some minor friction points and divergences in the Getting Started docs.

The Getting Started for Minikube instructions include section 1 step 3:

```
kubectl expose deployment hello-nginxdemo --type=NodePort --port=80
```

The corresponding step is skipped in the Getting Started for the other types.  For example, the Getting Started for Colima Kubernetes:
- mentions checking the output (on a different port)
- does not include the service in the manifest you're supposed to apply
- does not include the `kubectl expose` call.

As currently documented, the check will not succeed.

The Getting Started for Minikube instructions are less specific than the other "Getting Started"s about checking this output.

If you're running a local cluster and using MetalLB to provide a LoadBalancer, the command was:
```
kubectl expose deployment hello-nginxdemo --type=LoadBalancer --port=80
```

### What did you expect to happen?

see above

### Please provide the output of `gefyra check`.

n/a

### How can we reproduce it (as minimally and precisely as possible)?

see above

### What Kubernetes setup are you working with?

2.0.4

### OS version

n/a

**Comment by SteinRobert** [comment]
We added the port correction and expose command to the colima page, thank you!
